name: Makefile CI

on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
        - Ubuntu
        - Windows
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted, "${{ inputs.chosen-os }}"]

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make
    - name: Cleanup
      run: make clean
